services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs14-container
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@drizzle-db:5432/nextjs14_db
    depends_on:
      - drizzle-db
    restart: always

  drizzle-db:
    image: postgres:14
    container_name: nextjs14-drizzle-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nextjs14_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: