import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { headers } from "next/headers";
import { TRPCReactProvider } from "~/trpc/react";
import { NavBar } from "~/components/NavBar";

export const metadata: Metadata = {
  title: "Endless Kingdoms",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable} dark`}>
      <body className="bg-gray-900 text-gray-100 min-h-screen">
        <TRPCReactProvider headers={headers()}>
          <NavBar />
          <main className="container mx-auto mt-8 px-4">
            {children}
          </main>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
