import "~/styles/globals.css";

import { Inter } from 'next/font/google';
import { type Metadata } from "next";
import { headers } from "next/headers";
import { TRPCReactProvider } from "~/trpc/react";
import { SessionProvider } from "~/components/SessionProvider";

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Endless Kingdoms",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${inter.className} dark`}>
      <body className="bg-gray-900 text-gray-100 min-h-screen">
        <SessionProvider>
          <TRPCReactProvider headers={headers()}>
            {children}
          </TRPCReactProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
